version: '3'

services:

  web:
    container_name: web
    build: ./docker
    ports:
      - 8000:80
    privileged: true
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db-host
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    restart: always

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db-host
      - PMA_USER=root
      - PMA_PASSWORD=test
    ports:
      - 8080:80
    depends_on:
      - db

  redis:
    image: redis:alpine
    container_name: myapp-redis
    command: redis-server --appendonly yes
    volumes:
    - ./data/redis:/data
    ports:
      - "6379:6379"
